# fly.toml app configuration file generated for nixflymc on 2024-10-24T15:42:52-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nixflymc'
primary_region = 'den'

[[services]]
  protocol = 'tcp'
  internal_port = 25565
  auto_start_machines = true
  min_machines_running = 0

[[services.ports]]
    port = 25565

[[vm]]
  memory = '2GB'
  cpu_kind = 'shared'
  cpus = 1
